version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/app/data
      - ./backend/app/models:/app/app/models
    environment:
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - CALENDARIFIC_API_KEY=${CALENDARIFIC_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api 